// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: dfs.proto

package dfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUploadRequest) Reset() {
	*x = RequestUploadRequest{}
	mi := &file_dfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadRequest) ProtoMessage() {}

func (x *RequestUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadRequest.ProtoReflect.Descriptor instead.
func (*RequestUploadRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *RequestUploadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RequestUploadRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type RequestUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UploadId      string                 `protobuf:"bytes,3,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	KeeperId      string                 `protobuf:"bytes,4,opt,name=keeper_id,json=keeperId,proto3" json:"keeper_id,omitempty"`
	KeeperHost    string                 `protobuf:"bytes,5,opt,name=keeper_host,json=keeperHost,proto3" json:"keeper_host,omitempty"`
	KeeperTcpPort int32                  `protobuf:"varint,6,opt,name=keeper_tcp_port,json=keeperTcpPort,proto3" json:"keeper_tcp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUploadResponse) Reset() {
	*x = RequestUploadResponse{}
	mi := &file_dfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadResponse) ProtoMessage() {}

func (x *RequestUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadResponse.ProtoReflect.Descriptor instead.
func (*RequestUploadResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1}
}

func (x *RequestUploadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RequestUploadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RequestUploadResponse) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *RequestUploadResponse) GetKeeperId() string {
	if x != nil {
		return x.KeeperId
	}
	return ""
}

func (x *RequestUploadResponse) GetKeeperHost() string {
	if x != nil {
		return x.KeeperHost
	}
	return ""
}

func (x *RequestUploadResponse) GetKeeperTcpPort() int32 {
	if x != nil {
		return x.KeeperTcpPort
	}
	return 0
}

type HeartbeatRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	KeeperId          string                 `protobuf:"bytes,1,opt,name=keeper_id,json=keeperId,proto3" json:"keeper_id,omitempty"`
	GrpcAddr          string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"`
	Host              string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	TcpPort           int32                  `protobuf:"varint,4,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,5,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_dfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetKeeperId() string {
	if x != nil {
		return x.KeeperId
	}
	return ""
}

func (x *HeartbeatRequest) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *HeartbeatRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HeartbeatRequest) GetTcpPort() int32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_dfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SimpleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NotifyUploadCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	KeeperId      string                 `protobuf:"bytes,2,opt,name=keeper_id,json=keeperId,proto3" json:"keeper_id,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	RelativePath  string                 `protobuf:"bytes,4,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      string                 `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	IsReplication bool                   `protobuf:"varint,7,opt,name=is_replication,json=isReplication,proto3" json:"is_replication,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyUploadCompleteRequest) Reset() {
	*x = NotifyUploadCompleteRequest{}
	mi := &file_dfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyUploadCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyUploadCompleteRequest) ProtoMessage() {}

func (x *NotifyUploadCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyUploadCompleteRequest.ProtoReflect.Descriptor instead.
func (*NotifyUploadCompleteRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyUploadCompleteRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *NotifyUploadCompleteRequest) GetKeeperId() string {
	if x != nil {
		return x.KeeperId
	}
	return ""
}

func (x *NotifyUploadCompleteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *NotifyUploadCompleteRequest) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *NotifyUploadCompleteRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *NotifyUploadCompleteRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *NotifyUploadCompleteRequest) GetIsReplication() bool {
	if x != nil {
		return x.IsReplication
	}
	return false
}

type GetUploadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusRequest) Reset() {
	*x = GetUploadStatusRequest{}
	mi := &file_dfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusRequest) ProtoMessage() {}

func (x *GetUploadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetUploadStatusRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *GetUploadStatusRequest) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

type GetUploadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadStatusResponse) Reset() {
	*x = GetUploadStatusResponse{}
	mi := &file_dfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadStatusResponse) ProtoMessage() {}

func (x *GetUploadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadStatusResponse.ProtoReflect.Descriptor instead.
func (*GetUploadStatusResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *GetUploadStatusResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetUploadStatusResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *GetUploadStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DownloadTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTargetsRequest) Reset() {
	*x = DownloadTargetsRequest{}
	mi := &file_dfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTargetsRequest) ProtoMessage() {}

func (x *DownloadTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTargetsRequest.ProtoReflect.Descriptor instead.
func (*DownloadTargetsRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadTargetsRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DownloadTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeeperId      string                 `protobuf:"bytes,1,opt,name=keeper_id,json=keeperId,proto3" json:"keeper_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	TcpPort       int32                  `protobuf:"varint,3,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTarget) Reset() {
	*x = DownloadTarget{}
	mi := &file_dfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTarget) ProtoMessage() {}

func (x *DownloadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTarget.ProtoReflect.Descriptor instead.
func (*DownloadTarget) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadTarget) GetKeeperId() string {
	if x != nil {
		return x.KeeperId
	}
	return ""
}

func (x *DownloadTarget) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DownloadTarget) GetTcpPort() int32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

type DownloadTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Targets       []*DownloadTarget      `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTargetsResponse) Reset() {
	*x = DownloadTargetsResponse{}
	mi := &file_dfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTargetsResponse) ProtoMessage() {}

func (x *DownloadTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTargetsResponse.ProtoReflect.Descriptor instead.
func (*DownloadTargetsResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadTargetsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DownloadTargetsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DownloadTargetsResponse) GetTargets() []*DownloadTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type ReplicateFileRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Filename            string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	SourcePath          string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	DestinationKeeperId string                 `protobuf:"bytes,3,opt,name=destination_keeper_id,json=destinationKeeperId,proto3" json:"destination_keeper_id,omitempty"`
	DestinationHost     string                 `protobuf:"bytes,4,opt,name=destination_host,json=destinationHost,proto3" json:"destination_host,omitempty"`
	DestinationTcpPort  int32                  `protobuf:"varint,5,opt,name=destination_tcp_port,json=destinationTcpPort,proto3" json:"destination_tcp_port,omitempty"`
	Size                int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Checksum            string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReplicateFileRequest) Reset() {
	*x = ReplicateFileRequest{}
	mi := &file_dfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateFileRequest) ProtoMessage() {}

func (x *ReplicateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateFileRequest.ProtoReflect.Descriptor instead.
func (*ReplicateFileRequest) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{10}
}

func (x *ReplicateFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReplicateFileRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ReplicateFileRequest) GetDestinationKeeperId() string {
	if x != nil {
		return x.DestinationKeeperId
	}
	return ""
}

func (x *ReplicateFileRequest) GetDestinationHost() string {
	if x != nil {
		return x.DestinationHost
	}
	return ""
}

func (x *ReplicateFileRequest) GetDestinationTcpPort() int32 {
	if x != nil {
		return x.DestinationTcpPort
	}
	return 0
}

func (x *ReplicateFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReplicateFileRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ReplicateFileResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Ok                      bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error                   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DestinationRelativePath string                 `protobuf:"bytes,3,opt,name=destination_relative_path,json=destinationRelativePath,proto3" json:"destination_relative_path,omitempty"`
	BytesTransferred        int64                  `protobuf:"varint,4,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ReplicateFileResponse) Reset() {
	*x = ReplicateFileResponse{}
	mi := &file_dfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateFileResponse) ProtoMessage() {}

func (x *ReplicateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateFileResponse.ProtoReflect.Descriptor instead.
func (*ReplicateFileResponse) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{11}
}

func (x *ReplicateFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReplicateFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReplicateFileResponse) GetDestinationRelativePath() string {
	if x != nil {
		return x.DestinationRelativePath
	}
	return ""
}

func (x *ReplicateFileResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

var File_dfs_proto protoreflect.FileDescriptor

const file_dfs_proto_rawDesc = "" +
	"\n" +
	"\tdfs.proto\x12\x03dfs\"b\n" +
	"\x14RequestUploadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\"\xc0\x01\n" +
	"\x15RequestUploadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tupload_id\x18\x03 \x01(\tR\buploadId\x12\x1b\n" +
	"\tkeeper_id\x18\x04 \x01(\tR\bkeeperId\x12\x1f\n" +
	"\vkeeper_host\x18\x05 \x01(\tR\n" +
	"keeperHost\x12&\n" +
	"\x0fkeeper_tcp_port\x18\x06 \x01(\x05R\rkeeperTcpPort\"\xab\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tkeeper_id\x18\x01 \x01(\tR\bkeeperId\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x19\n" +
	"\btcp_port\x18\x04 \x01(\x05R\atcpPort\x12.\n" +
	"\x13timestamp_unix_nano\x18\x05 \x01(\x03R\x11timestampUnixNano\"6\n" +
	"\x0eSimpleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xef\x01\n" +
	"\x1bNotifyUploadCompleteRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1b\n" +
	"\tkeeper_id\x18\x02 \x01(\tR\bkeeperId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12#\n" +
	"\rrelative_path\x18\x04 \x01(\tR\frelativePath\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12%\n" +
	"\x0eis_replication\x18\a \x01(\bR\risReplication\"5\n" +
	"\x16GetUploadStatusRequest\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\"c\n" +
	"\x17GetUploadStatusResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"4\n" +
	"\x16DownloadTargetsRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\\\n" +
	"\x0eDownloadTarget\x12\x1b\n" +
	"\tkeeper_id\x18\x01 \x01(\tR\bkeeperId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x19\n" +
	"\btcp_port\x18\x03 \x01(\x05R\atcpPort\"n\n" +
	"\x17DownloadTargetsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\atargets\x18\x03 \x03(\v2\x13.dfs.DownloadTargetR\atargets\"\x94\x02\n" +
	"\x14ReplicateFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x122\n" +
	"\x15destination_keeper_id\x18\x03 \x01(\tR\x13destinationKeeperId\x12)\n" +
	"\x10destination_host\x18\x04 \x01(\tR\x0fdestinationHost\x120\n" +
	"\x14destination_tcp_port\x18\x05 \x01(\x05R\x12destinationTcpPort\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\"\xa6\x01\n" +
	"\x15ReplicateFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12:\n" +
	"\x19destination_relative_path\x18\x03 \x01(\tR\x17destinationRelativePath\x12+\n" +
	"\x11bytes_transferred\x18\x04 \x01(\x03R\x10bytesTransferred2\xfe\x02\n" +
	"\rMasterService\x12F\n" +
	"\rRequestUpload\x12\x19.dfs.RequestUploadRequest\x1a\x1a.dfs.RequestUploadResponse\x127\n" +
	"\tHeartbeat\x12\x15.dfs.HeartbeatRequest\x1a\x13.dfs.SimpleResponse\x12M\n" +
	"\x14NotifyUploadComplete\x12 .dfs.NotifyUploadCompleteRequest\x1a\x13.dfs.SimpleResponse\x12L\n" +
	"\x0fGetUploadStatus\x12\x1b.dfs.GetUploadStatusRequest\x1a\x1c.dfs.GetUploadStatusResponse\x12O\n" +
	"\x12GetDownloadTargets\x12\x1b.dfs.DownloadTargetsRequest\x1a\x1c.dfs.DownloadTargetsResponse2[\n" +
	"\x11DataKeeperService\x12F\n" +
	"\rReplicateFile\x12\x19.dfs.ReplicateFileRequest\x1a\x1a.dfs.ReplicateFileResponseB>Z<github.com/El-Maktab/distributed-file-system/pkg/api/dfs;dfsb\x06proto3"

var (
	file_dfs_proto_rawDescOnce sync.Once
	file_dfs_proto_rawDescData []byte
)

func file_dfs_proto_rawDescGZIP() []byte {
	file_dfs_proto_rawDescOnce.Do(func() {
		file_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)))
	})
	return file_dfs_proto_rawDescData
}

var file_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_dfs_proto_goTypes = []any{
	(*RequestUploadRequest)(nil),        // 0: dfs.RequestUploadRequest
	(*RequestUploadResponse)(nil),       // 1: dfs.RequestUploadResponse
	(*HeartbeatRequest)(nil),            // 2: dfs.HeartbeatRequest
	(*SimpleResponse)(nil),              // 3: dfs.SimpleResponse
	(*NotifyUploadCompleteRequest)(nil), // 4: dfs.NotifyUploadCompleteRequest
	(*GetUploadStatusRequest)(nil),      // 5: dfs.GetUploadStatusRequest
	(*GetUploadStatusResponse)(nil),     // 6: dfs.GetUploadStatusResponse
	(*DownloadTargetsRequest)(nil),      // 7: dfs.DownloadTargetsRequest
	(*DownloadTarget)(nil),              // 8: dfs.DownloadTarget
	(*DownloadTargetsResponse)(nil),     // 9: dfs.DownloadTargetsResponse
	(*ReplicateFileRequest)(nil),        // 10: dfs.ReplicateFileRequest
	(*ReplicateFileResponse)(nil),       // 11: dfs.ReplicateFileResponse
}
var file_dfs_proto_depIdxs = []int32{
	8,  // 0: dfs.DownloadTargetsResponse.targets:type_name -> dfs.DownloadTarget
	0,  // 1: dfs.MasterService.RequestUpload:input_type -> dfs.RequestUploadRequest
	2,  // 2: dfs.MasterService.Heartbeat:input_type -> dfs.HeartbeatRequest
	4,  // 3: dfs.MasterService.NotifyUploadComplete:input_type -> dfs.NotifyUploadCompleteRequest
	5,  // 4: dfs.MasterService.GetUploadStatus:input_type -> dfs.GetUploadStatusRequest
	7,  // 5: dfs.MasterService.GetDownloadTargets:input_type -> dfs.DownloadTargetsRequest
	10, // 6: dfs.DataKeeperService.ReplicateFile:input_type -> dfs.ReplicateFileRequest
	1,  // 7: dfs.MasterService.RequestUpload:output_type -> dfs.RequestUploadResponse
	3,  // 8: dfs.MasterService.Heartbeat:output_type -> dfs.SimpleResponse
	3,  // 9: dfs.MasterService.NotifyUploadComplete:output_type -> dfs.SimpleResponse
	6,  // 10: dfs.MasterService.GetUploadStatus:output_type -> dfs.GetUploadStatusResponse
	9,  // 11: dfs.MasterService.GetDownloadTargets:output_type -> dfs.DownloadTargetsResponse
	11, // 12: dfs.DataKeeperService.ReplicateFile:output_type -> dfs.ReplicateFileResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_dfs_proto_init() }
func file_dfs_proto_init() {
	if File_dfs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dfs_proto_rawDesc), len(file_dfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dfs_proto_goTypes,
		DependencyIndexes: file_dfs_proto_depIdxs,
		MessageInfos:      file_dfs_proto_msgTypes,
	}.Build()
	File_dfs_proto = out.File
	file_dfs_proto_goTypes = nil
	file_dfs_proto_depIdxs = nil
}
